/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Pavaree
 */
public class Home extends javax.swing.JInternalFrame {
    private TravelRookie u;
    public String place ="";
    /**
     * Creates new form Home
     */
    public Home(){
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }
    public Home(TravelRookie got) {
        this.u = got;
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page_home = new javax.swing.JPanel();
        img_travelrookie = new javax.swing.JLabel();
        TravelRookie = new javax.swing.JLabel();
        choose_txt = new javax.swing.JLabel();
        choose_country = new javax.swing.JComboBox<>();
        Lets_go = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(930, 630));

        page_home.setBackground(new java.awt.Color(231, 123, 165));
        page_home.setPreferredSize(new java.awt.Dimension(930, 630));

        img_travelrookie.setForeground(new java.awt.Color(255, 255, 255));
        img_travelrookie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_imges/410QlxiASbL.png"))); // NOI18N

        TravelRookie.setFont(new java.awt.Font("Harlow Solid Italic", 0, 55)); // NOI18N
        TravelRookie.setForeground(new java.awt.Color(255, 255, 255));
        TravelRookie.setText("TravelRookie");

        choose_txt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        choose_txt.setForeground(new java.awt.Color(255, 255, 255));
        choose_txt.setText("Choose your place to travel !");

        choose_country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Australia", "Canada", "China", "Croatia", "Denmark", "Hungary", "Iceland", "Indonesia", "Japan", "Korea", "Mexico", "Norway", "Singapore", "South Africa", "Sweden", "Switzerland", "Thailand", "Turkey", "United Kingdom", "United States" }));
        choose_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_countryActionPerformed(evt);
            }
        });

        Lets_go.setBackground(new java.awt.Color(255, 255, 255));
        Lets_go.setText("Let's Go");
        Lets_go.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lets_goMouseClicked(evt);
            }
        });
        Lets_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lets_goActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page_homeLayout = new javax.swing.GroupLayout(page_home);
        page_home.setLayout(page_homeLayout);
        page_homeLayout.setHorizontalGroup(
            page_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page_homeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(img_travelrookie)
                .addGroup(page_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page_homeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(choose_txt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(page_homeLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(TravelRookie)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(page_homeLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Lets_go, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(page_homeLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(choose_country, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        page_homeLayout.setVerticalGroup(
            page_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page_homeLayout.createSequentialGroup()
                .addGroup(page_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page_homeLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(TravelRookie, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(choose_txt)
                        .addGap(58, 58, 58)
                        .addComponent(choose_country, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(Lets_go))
                    .addGroup(page_homeLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(img_travelrookie)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page_home, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choose_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choose_countryActionPerformed

    private void Lets_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lets_goActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lets_goActionPerformed

    private void Lets_goMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lets_goMouseClicked
        u.setColor(u.getBtn_time_emp());
        u.resetColor(u.getBtn_home());
        page_home.removeAll();
        place = choose_country.getSelectedItem().toString();
        Time t = new Time(this);
        u.setPlace(place);
        u.btn_place.setVisible(true);
        u.btn_money.setVisible(true);
        u.btn_time_emp.setVisible(true);
        page_home.add(t).setVisible(true);
    }//GEN-LAST:event_Lets_goMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lets_go;
    private javax.swing.JLabel TravelRookie;
    private javax.swing.JComboBox<String> choose_country;
    private javax.swing.JLabel choose_txt;
    private javax.swing.JLabel img_travelrookie;
    private javax.swing.JPanel page_home;
    // End of variables declaration//GEN-END:variables
}
