/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Pavaree
 */
public class Place extends javax.swing.JInternalFrame {

    TravelRookie page;

    /**
     * Creates new form Place
     */
    public Place() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

    }

    public Place(TravelRookie in) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        this.page = in;
        System.out.println(page.place);
        showInfo();
    }

    public void showInfo() {
        String path = "../place_image/australia/bondibeach.jpg";
        
        if (page.place.equals("Australia")){
            img1.setIcon(new ImageIcon("src\\place_image_australia\\bondibeach.jpg"));
            img1.setText("enter text here");
            img2.setIcon(new ImageIcon("src\\place_image_australia\\12apostles.jpg"));
            img2.setText("enter text here");
            img3.setIcon(new ImageIcon("src\\place_image_australia\\sydneyopera.jpg"));
            img3.setText("enter text here");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Page_place = new javax.swing.JPanel();
        txt_recommended = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        season1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        season2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        season3 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(930, 630));

        Page_place.setBackground(new java.awt.Color(3, 151, 161));
        Page_place.setPreferredSize(new java.awt.Dimension(930, 630));
        Page_place.setRequestFocusEnabled(false);

        txt_recommended.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        txt_recommended.setForeground(new java.awt.Color(255, 255, 255));
        txt_recommended.setText("Recommended Place");

        name1.setText("name1");

        season1.setText("season1");

        img2.setText("img2");

        name2.setText("name2");

        season2.setText("season2");

        img3.setText("img3");

        name3.setText("name3");

        season3.setText("season3");

        img1.setText("img1");
        img1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout Page_placeLayout = new javax.swing.GroupLayout(Page_place);
        Page_place.setLayout(Page_placeLayout);
        Page_placeLayout.setHorizontalGroup(
            Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page_placeLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(txt_recommended)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Page_placeLayout.createSequentialGroup()
                .addGroup(Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Page_placeLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name1)
                            .addComponent(season1)))
                    .addGroup(Page_placeLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125)
                .addGroup(Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Page_placeLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name2)
                            .addComponent(season2)))
                    .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Page_placeLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(season3)
                            .addComponent(name3)))
                    .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        Page_placeLayout.setVerticalGroup(
            Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page_placeLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(txt_recommended, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Page_placeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Page_placeLayout.createSequentialGroup()
                        .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name1)
                        .addGap(50, 50, 50)
                        .addComponent(season1))
                    .addGroup(Page_placeLayout.createSequentialGroup()
                        .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name2)
                        .addGap(50, 50, 50)
                        .addComponent(season2))
                    .addGroup(Page_placeLayout.createSequentialGroup()
                        .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name3)
                        .addGap(50, 50, 50)
                        .addComponent(season3)))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Page_place, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Page_place, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Page_place;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel season1;
    private javax.swing.JLabel season2;
    private javax.swing.JLabel season3;
    private javax.swing.JLabel txt_recommended;
    // End of variables declaration//GEN-END:variables
}
